name : my_first_workflow
on : push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "HelloWorld!"
      - name: list files
        run: ls -la
      - name: Read the file
        run: cat test
