name : my_first_workflow
on : push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "HelloWorld!"
      - name: list files
        run: ls
        